version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=name_app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: name_app
    volumes:
      - ./name_app.sql:/docker-entrypoint-initdb.d/name_app.sql
